# Generated by Django 4.0.4 on 2022-06-07 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('posting_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True)),
                ('description', models.TextField()),
                ('country', models.CharField(blank=True, max_length=32)),
                ('city', models.CharField(blank=True, max_length=32)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('creation_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('login', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=32, unique=True)),
                ('avatar', models.ImageField(blank=True, upload_to='images/users')),
                ('name', models.CharField(max_length=32)),
                ('surname', models.CharField(max_length=32)),
                ('birthday', models.DateField()),
                ('country', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=32)),
                ('profession', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True)),
                ('signup_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('wage', models.IntegerField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseCommunication.project')),
            ],
        ),
        migrations.CreateModel(
            name='VacancyReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseCommunication.user')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseCommunication.vacancy')),
            ],
        ),
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseCommunication.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseCommunication.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=32)),
                ('link', models.URLField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseCommunication.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseCommunication.language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseCommunication.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=100)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('degree', models.CharField(max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseCommunication.user')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseCommunication.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseCommunication.user')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseCommunication.project')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseCommunication.tag')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseCommunication.language')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseCommunication.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/projects')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseCommunication.project')),
            ],
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/news')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseCommunication.news')),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseCommunication.project'),
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.BooleanField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseCommunication.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseCommunication.user')),
            ],
            options={
                'unique_together': {('user', 'project')},
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_owner', models.BooleanField(default=False)),
                ('position', models.CharField(max_length=32)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseCommunication.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseCommunication.user')),
            ],
            options={
                'unique_together': {('user', 'project')},
            },
        ),
    ]
